insert
	into
		TM_ROAD(
			company_code,
			werks,
			afdeling_code,
			block_code,
			road_code,
			road_name,
			status_pekerasan,
			status_aktif,
			deleted_at,
			created_at,
			updated_at,
			estate_code,
			updated_by,
			total_length,
			asset_code,
			segment,
			status_id,
			category_id
		)(
			select
				company_code,
				werks,
				afdeling_code,
				block_code,
				'DUMMYDATA',
				road_name,
				status_pekerasan,
				status_aktif,
				deleted_at,
				created_at,
				updated_at,
				estate_code,
				updated_by,
				total_length,
				asset_code,
				segment,
				status_id,
				category_id
			from
				TM_ROAD
		)